name: Android Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.6
          cache: 'gradle'
          distribution: adopt
      - name: Run Tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build